language: python

python:
  - "2.7"

env:
  -DJANGO=1.9.2 MIGRATE='./manage.py migrate' DB=sqlite

install:
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - python manage.py test