addons:
  firefox: latest-unsigned
  
language: python

python:
  - "2.7"

env:
  -DJANGO=1.9.2 DB=sqlite

install:
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - python manage.py collectstatic --noinput
  - python manage.py test --settings=bugheist.settings

